services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: careerpath
      POSTGRES_PASSWORD: careerpath
      POSTGRES_USER: careerpath
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev:/var/lib/postgresql/data

volumes:
  postgres_dev:
